### ISSUE TITLE
Patch script failed, had to adapt to proceed with build process

### ISSUE THREAD

**Issue by Elvyria** [hyprwm/wlroots-hyprland#10]
Was in the process of updating to Hyprland 0.40.0, build was crashing with:
```
meson.build:83:11: ERROR: Command `/builddir/hyprland-0.40.0/subprojects/wlroots-hyprland/./patches/apply.sh` failed with status 1.
```
Had to open up meson-log.txt to find out what's wrong (so you might want to do something about it, because users probably wont go that far and you'll have to ask..)
```
--- stderr ---
fatal: not a git repository: /builddir/hyprland-0.40.0/subprojects/wlroots-hyprland/../../.git/modules/subprojects/wlroots-hyprland
fatal: not a git repository: /builddir/hyprland-0.40.0/subprojects/wlroots-hyprland/../../.git/modules/subprojects/wlroots-hyprland
```
Fixed by replacing `git apply $PATCH` with `patch -p1 < $PATCH` in a build [patch](https://github.com/Elvyria/voids-package-nightmare/blob/e9c832a7b7b85772c971acaacffd7ce525385d4d/srcpkgs/hyprland/patches/patch-script.patch).

I'm building from source tar ball of a release ([source-v0.40.0.tar.gz](https://github.com/hyprwm/Hyprland/releases/download/v0.40.0/source-v0.40.0.tar.gz)) trough cmake, nothing complicated really ([package template](https://github.com/Elvyria/voids-package-nightmare/blob/e9c832a7b7b85772c971acaacffd7ce525385d4d/srcpkgs/hyprland/template)), although Void builds packages in a chroot jail.

Just a heads up, not sure if you want to do anything about it, just felt wrong not to report.

PS: Only now noticed, probably related: (https://github.com/hyprwm/Hyprland/issues/5898)

**Comment by vaxerski** [comment]
probably how it should've been anyways.

MRs welcome. @fufexan could you do it and test the stuff?

**Comment by Agent00Ming** [comment]
The check applied function is needed if compiling from the same source multiple times or else it will fail to apply every time after the first time any patch is applied.

**Comment by Agent00Ming** [comment]
Please have a look at #11
