### ISSUE TITLE
Disable xwl's blurry fractional scaling by default

### ISSUE THREAD

**Issue by fubuki4649** [hyprwm/wlroots-hyprland#6]
Currently, xwayland tries to do fractional scaling but fails miserably, causing the app to be blurry and unusable on hidpi monitors with fractional scaling.

An alternative solution that has been proposed, is to force xwayland to not attempt to fractionally scale at all, instead rendering everything at 1x and letting the individual app handle scaling instead (which is how things are usually done in X).

There has been a series of (working) patches for xwayland and wlroots for a while now, but was never merged due to excessive unproductive discussion by the gentlemen at freedesktop:

- https://aur.archlinux.org/packages/hyprland-hidpi-xprop-git
- https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/733

In light of the recent emancipation of the Hyprland project from freedesktop, I believe that these changes can be merged into the new hyprland fork of wlroots and xwl (which currently doesn't exist yet).

**Comment by vaxerski** [comment]
this is already a feature in hyprland but it's off by default. RTFM, especially the xwayland section
